### ISSUE TITLE
Firewall rule crash

### ISSUE THREAD

**Issue by david082321** [hklcf/Adhell3#6]
`java.lang.Exception: Failed to add/update rule in the database. / The specified package name is not installed.
	at com.fusionjack.adhell3.utils.FirewallUtils.handleResponse(FirewallUtils.java:193)
	at com.fusionjack.adhell3.utils.FirewallUtils.addFirewallRules(FirewallUtils.java:59)
	at com.fusionjack.adhell3.blocker.ContentBlocker56.processMobileRestrictedApps(ContentBlocker56.java:248)
	at com.fusionjack.adhell3.blocker.ContentBlocker56.enableFirewallRules(ContentBlocker56.java:69)
	at com.fusionjack.adhell3.fragments.HomeTabFragment$SetFirewallAsyncTask.doInBackground(HomeTabFragment.java:422)
	at com.fusionjack.adhell3.fragments.HomeTabFragment$SetFirewallAsyncTask.doInBackground(HomeTabFragment.java:372)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)`

**Comment by david082321** [comment]
i disable an app in Apps Management -> Mobile Data, and then uninstall the app.
then, i open Firewall Rule in Home page.

can you automatic remove uninstalled app in the blacklist?
